### ISSUE TITLE
Cannot Register

### ISSUE THREAD

**Issue by jurgens37** [NickKvizhinadze/DatingApp#1]

**Comment by NickKvizhinadze** [comment]
I tried and it works, did you start api?

**Comment by jurgens37** [comment]
Here are the screenshots of the errors provided when I want to register or sign up 
![screenshot_10](https://user-images.githubusercontent.com/17015640/41817941-0041544a-77a5-11e8-90e3-0bff623afc22.png)

![screenshot_11](https://user-images.githubusercontent.com/17015640/41817946-0b639310-77a5-11e8-8635-d7b17651de7b.png)

**Comment by NickKvizhinadze** [comment]
You have to start DatingApp.Api project, (Asp.net web api), after that it will work properly. :)

**Comment by jurgens37** [comment]
Ive start it.. these screenshots are taken after ive setup your project in my local environment..

**Comment by jurgens37** [comment]
The problem is that the console does not show any type of error :O
